author: Michael Hadley
description: Nothing much
encoding: utf-8
kramdown:
  input: GFM
title: mthadley
name: mthadley
timezone: America/Los_Angeles
url: https://mthadley.github.io
gems:
  - jekyll-seo-tag
