author:
  name: Michael Hadley
  twitter: mikethadley
description: Nothing much
encoding: utf-8
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
kramdown:
  input: GFM
name: mthadley
title: mthadley
timezone: America/Los_Angeles
twitter:
  username: mikethadley
url: mthadley.com
